version: 2.1
jobs:
    build:
        docker:
            - image: cimg/php:8.3-browsers
        steps:
            - checkout
            - run:
                  name: autoreconf
                  command: sudo apt install automake
            - run:
                  name: install
                  command: yarn
            - run:
                  name: lint
                  command: yarn lint
            - run:
                  name: pwa
                  command: yarn pwa
            - run:
                  name: prod
                  command: yarn prod
